steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.herald', '-t', 'gcr.io/living-swarm-prod/fleet-herald:latest', '.']
images: ['gcr.io/living-swarm-prod/fleet-herald:latest']
